live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "SFMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 14
y = 14
