
add_newline = false
format = """$directory$character"""
right_format = """$all"""


[rust]
symbol = "î¨"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[package]
disabled = true

[git_status]
conflicted = 'ğŸ³'
untracked = '[?\($count\)](red)'
modified = '[!\($count\)](blue)'
staged = '[++\($count\)](green)'
